### ISSUE TITLE
notification not been received when app is closed

### ISSUE THREAD

**Issue by gbelvedere** [redjanym/FCMBundle#25] opened 2018-11-30 12:55 UTC
When the app is closed the notifications are not being received, any way to pass something like force-start?

**Comment by redjanym** [comment] 2018-12-04 21:10
What is your client? Android, iOS or Web(Javascript SDK)?

**Comment by gbelvedere** [comment] 2018-12-05 08:43
The client is Android. 
I think I've fixed it doing: 

`            
$extraData = [];
$extraData['force-start'] = 1;
$notification->setData($extraData);
`
looks correct?

**Comment by redjanym** [comment] 2018-12-07 11:44
Normally it should be sent without the need to add a force-start parameter. Are you sure the issue is not on App side? Have you added any log to understand maybe message comes but it is the final generation of the notification which does not work?

**Comment by redjanym** [comment] 2018-12-19 20:03
Considering issue as resolved and closing it after not having more feedback.

**Closed as completed by redjanym** 2018-12-19 20:03 UTC
